spring:
  application:
    name: user-service
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/userdb}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}  

management:
    endpoints:
        web:
            exposure:
                include: health
    endpoint:
        health:
            show-details: always